CREATE SCHEMA IF NOT EXISTS providentia;

CREATE TABLE IF NOT EXISTS providentia.ExerciseFocus (
	ID SERIAL PRIMARY KEY NOT NULL,
	Focus TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS providentia.ExerciseType (
	ID SERIAL NOT NULL PRIMARY KEY,
	Kind TEXT NOT NULL,
	Description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS providentia.Exercise (
	ID SERIAL NOT NULL PRIMARY KEY,
	Name TEXT NOT NULL,
	TypeID INT NOT NULL REFERENCES providentia.ExerciseType(ID),
	FocusID INT NOT NULL REFERENCES providentia.ExerciseFocus(ID)
);

CREATE TABLE IF NOT EXISTS providentia.Client (
	ID SERIAL NOT NULL PRIMARY KEY,
	FirstName TEXT NOT NULL,
	LastName TEXT NOT NULL,
	Email TEXT NOT NULL
);
