#ifndef CGO_GLUE_INCLUDE_GUARD
#define CGO_GLUE_INCLUDE_GUARD

// File generated by cgoGlue - DO NOT EDIT
// Type definitions generated for C from Go type definitions

#include <math.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

	enum ApproximationError_t : int32_t {
		SecondOrder = 2,
		FourthOrder = 4
	};

	enum BarPathCalcErrCode_t : int64_t {
		NoErr = 0,
		TimeSeriesNotIncreasingErr = 1,
		TimeSeriesNotMonotonicErr = 2,
		InvalidApproximationErrErr = 3
	};

	typedef struct accPointInTime{
		double_t Time;
		double_t Value;
	} accPointInTime_t;

	typedef struct accVec2{
		double_t X;
		double_t Y;
	} accVec2_t;

	typedef struct barPathCalcHyperparams{
		int32_t Version;
		uint64_t MinNumSamples;
		double_t TimeDeltaEps;
		enum ApproximationError_t ApproxErr;
		double_t NearZeroFilter;
		double_t SmootherWeight1;
		double_t SmootherWeight2;
		double_t SmootherWeight3;
		double_t SmootherWeight4;
		double_t SmootherWeight5;
	} barPathCalcHyperparams_t;

	typedef struct forceVec2{
		double_t X;
		double_t Y;
	} forceVec2_t;

	typedef struct impulseVec2{
		double_t X;
		double_t Y;
	} impulseVec2_t;

	typedef struct jerkPointInTime{
		double_t Time;
		double_t Value;
	} jerkPointInTime_t;

	typedef struct jerkVec2{
		double_t X;
		double_t Y;
	} jerkVec2_t;

	typedef struct joulePointInTime{
		double_t Time;
		double_t Value;
	} joulePointInTime_t;

	typedef struct newtonPointInTime{
		double_t Time;
		double_t Value;
	} newtonPointInTime_t;

	typedef struct newtonSecPointInTime{
		double_t Time;
		double_t Value;
	} newtonSecPointInTime_t;

	typedef struct posVec2{
		double_t X;
		double_t Y;
	} posVec2_t;

	typedef struct split{
		int64_t StartIdx;
		int64_t EndIdx;
	} split_t;

	typedef struct velPointInTime{
		double_t Time;
		double_t Value;
	} velPointInTime_t;

	typedef struct velVec2{
		double_t X;
		double_t Y;
	} velVec2_t;

	typedef struct wattPointInTime{
		double_t Time;
		double_t Value;
	} wattPointInTime_t;

	typedef struct barPathData{
		double_t mass;
		int64_t timeLen;
		double_t* time;
		posVec2_t* pos;
		velVec2_t* vel;
		accVec2_t* acc;
		jerkVec2_t* jerk;
		forceVec2_t* force;
		impulseVec2_t* impulse;
		double_t* power;
		double_t* work;
		int32_t reps;
		split_t* repSplit;
		velPointInTime_t* minVel;
		velPointInTime_t* maxVel;
		accPointInTime_t* minAcc;
		accPointInTime_t* maxAcc;
		newtonPointInTime_t* minForce;
		newtonPointInTime_t* maxForce;
		newtonSecPointInTime_t* minImpulse;
		newtonSecPointInTime_t* maxImpulse;
		double_t* avgWork;
		joulePointInTime_t* minWork;
		joulePointInTime_t* maxWork;
		double_t* avgPower;
		wattPointInTime_t* minPower;
		wattPointInTime_t* maxPower;
	} barPathData_t;

#ifdef __cplusplus
}
#endif

#endif
