
// File generated by cgoGlue - DO NOT EDIT
// Generated by:
//   File: ./gen/main.go
//   Line: 15
//
// Function declarations generated by scraping C and CPP files for functions that
// match the following signatures:
//  - For C files  : bool Test<funcName>(void)
//  - For CPP files: extern "C" bool Test<funcName>(void)

#ifndef CLIB_CLIB_TESTS
#define CLIB_CLIB_TESTS

#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif


bool TestMaxHeap(void);

bool TestMaxHeapSingleElementSlice(void);

bool TestMinHeap(void);

bool TestMinHeapSingleElementSlice(void);

bool TestSlicePointerConstructor(void);

bool TestSliceBracketOperator(void);

bool TestSliceSubslice(void);

bool TestSliceIterator(void);

bool TestFixedSlicePointerConstructor(void);

bool TestFixedSliceWholeSliceConstructor(void);

bool TestFixedSliceSubSliceConstructor(void);

bool TestFixedSliceBracketOperator(void);

bool TestFixedSliceSubslice(void);

bool TestFixedSliceIterator(void);

bool TestFixedRingPointerConstructor(void);

bool TestFixedRingFixedSliceConstructor(void);

bool TestFixedRingSliceConstructor(void);

bool TestFixedRingSubSliceConstructor(void);

bool TestFixedRingPut(void);

bool TestFixedRingIterator(void);

bool TestAssociatedSlicesConstructor(void);

bool TestFirstDerivativeVec2SecondOrder(void);

bool TestFirstDerivativeVec2FourthOrder(void);

bool TestSecondDerivativeVec2SecondOrder(void);

bool TestSecondDerivativeVec2FourthOrder(void);

bool TestThirdDerivativeVec2SecondOrder(void);

bool TestThirdDerivativeVec2FourthOrder(void);

bool TestWeightedAvgVec2(void);

bool TestWeightedAvgVec2WeightProvided(void);

bool TestCenteredRollingWeightedAvgVec2WeightsSumToZero(void);

bool TestCenteredRollingWeightedAvgVec2(void);

bool TestNSmallestMinimumsMoreExpectedThanPresent(void);

bool TestNSmallestMinimumsMorePresentThanExpected(void);

bool TestNSmallestMinimumsLargerWindow(void);

bool TestNLargestMaximumsMoreExpectedThanPresent(void);

bool TestNLargestMaximumssMorePresentThanExpected(void);

bool TestNLargestMaximumsLargerWindow(void);

bool TestLeftRoot(void);


#ifdef __cplusplus
}
#endif

#endif
