package clib

// File generated by cgoTest - DO NOT EDIT
// List of tests generated by scraping C and CPP files for functions that match
// the following signatures:
//  - For C files  : bool Test<funcName>(void)
//  - For CPP files: extern "C" bool Test<funcName>(void)

// #cgo CXXFLAGS: -Wall -march=native -std=c++23
// #cgo LDFLAGS: -lstdc++
// #include "tests.gen.h"
import "C"
import "testing"

func runCgoTests(t *testing.T) {

	t.Run("MaxHeap", func(t *testing.T) {
		if !C.TestMaxHeap() {
			t.Fatal()
		}
	})

	t.Run("MaxHeapSingleElementSlice", func(t *testing.T) {
		if !C.TestMaxHeapSingleElementSlice() {
			t.Fatal()
		}
	})

	t.Run("MinHeap", func(t *testing.T) {
		if !C.TestMinHeap() {
			t.Fatal()
		}
	})

	t.Run("MinHeapSingleElementSlice", func(t *testing.T) {
		if !C.TestMinHeapSingleElementSlice() {
			t.Fatal()
		}
	})

	t.Run("SlicePointerConstructor", func(t *testing.T) {
		if !C.TestSlicePointerConstructor() {
			t.Fatal()
		}
	})

	t.Run("SliceBracketOperator", func(t *testing.T) {
		if !C.TestSliceBracketOperator() {
			t.Fatal()
		}
	})

	t.Run("SliceSubslice", func(t *testing.T) {
		if !C.TestSliceSubslice() {
			t.Fatal()
		}
	})

	t.Run("SliceIterator", func(t *testing.T) {
		if !C.TestSliceIterator() {
			t.Fatal()
		}
	})

	t.Run("FixedSlicePointerConstructor", func(t *testing.T) {
		if !C.TestFixedSlicePointerConstructor() {
			t.Fatal()
		}
	})

	t.Run("FixedSliceWholeSliceConstructor", func(t *testing.T) {
		if !C.TestFixedSliceWholeSliceConstructor() {
			t.Fatal()
		}
	})

	t.Run("FixedSliceSubSliceConstructor", func(t *testing.T) {
		if !C.TestFixedSliceSubSliceConstructor() {
			t.Fatal()
		}
	})

	t.Run("FixedSliceBracketOperator", func(t *testing.T) {
		if !C.TestFixedSliceBracketOperator() {
			t.Fatal()
		}
	})

	t.Run("FixedSliceSubslice", func(t *testing.T) {
		if !C.TestFixedSliceSubslice() {
			t.Fatal()
		}
	})

	t.Run("FixedSliceIterator", func(t *testing.T) {
		if !C.TestFixedSliceIterator() {
			t.Fatal()
		}
	})

	t.Run("FixedRingPointerConstructor", func(t *testing.T) {
		if !C.TestFixedRingPointerConstructor() {
			t.Fatal()
		}
	})

	t.Run("FixedRingFixedSliceConstructor", func(t *testing.T) {
		if !C.TestFixedRingFixedSliceConstructor() {
			t.Fatal()
		}
	})

	t.Run("FixedRingSliceConstructor", func(t *testing.T) {
		if !C.TestFixedRingSliceConstructor() {
			t.Fatal()
		}
	})

	t.Run("FixedRingSubSliceConstructor", func(t *testing.T) {
		if !C.TestFixedRingSubSliceConstructor() {
			t.Fatal()
		}
	})

	t.Run("FixedRingPut", func(t *testing.T) {
		if !C.TestFixedRingPut() {
			t.Fatal()
		}
	})

	t.Run("FixedRingIterator", func(t *testing.T) {
		if !C.TestFixedRingIterator() {
			t.Fatal()
		}
	})

	t.Run("AssociatedSlicesConstructor", func(t *testing.T) {
		if !C.TestAssociatedSlicesConstructor() {
			t.Fatal()
		}
	})

	t.Run("FirstDerivativeVec2SecondOrder", func(t *testing.T) {
		if !C.TestFirstDerivativeVec2SecondOrder() {
			t.Fatal()
		}
	})

	t.Run("FirstDerivativeVec2FourthOrder", func(t *testing.T) {
		if !C.TestFirstDerivativeVec2FourthOrder() {
			t.Fatal()
		}
	})

	t.Run("SecondDerivativeVec2SecondOrder", func(t *testing.T) {
		if !C.TestSecondDerivativeVec2SecondOrder() {
			t.Fatal()
		}
	})

	t.Run("SecondDerivativeVec2FourthOrder", func(t *testing.T) {
		if !C.TestSecondDerivativeVec2FourthOrder() {
			t.Fatal()
		}
	})

	t.Run("ThirdDerivativeVec2SecondOrder", func(t *testing.T) {
		if !C.TestThirdDerivativeVec2SecondOrder() {
			t.Fatal()
		}
	})

	t.Run("ThirdDerivativeVec2FourthOrder", func(t *testing.T) {
		if !C.TestThirdDerivativeVec2FourthOrder() {
			t.Fatal()
		}
	})

	t.Run("WeightedAvgVec2", func(t *testing.T) {
		if !C.TestWeightedAvgVec2() {
			t.Fatal()
		}
	})

	t.Run("WeightedAvgVec2WeightProvided", func(t *testing.T) {
		if !C.TestWeightedAvgVec2WeightProvided() {
			t.Fatal()
		}
	})

	t.Run("CenteredRollingWeightedAvgVec2WeightsSumToZero", func(t *testing.T) {
		if !C.TestCenteredRollingWeightedAvgVec2WeightsSumToZero() {
			t.Fatal()
		}
	})

	t.Run("CenteredRollingWeightedAvgVec2", func(t *testing.T) {
		if !C.TestCenteredRollingWeightedAvgVec2() {
			t.Fatal()
		}
	})

	t.Run("NSmallestMinimumsMoreExpectedThanPresent", func(t *testing.T) {
		if !C.TestNSmallestMinimumsMoreExpectedThanPresent() {
			t.Fatal()
		}
	})

	t.Run("NSmallestMinimumsMorePresentThanExpected", func(t *testing.T) {
		if !C.TestNSmallestMinimumsMorePresentThanExpected() {
			t.Fatal()
		}
	})

	t.Run("NSmallestMinimumsLargerWindow", func(t *testing.T) {
		if !C.TestNSmallestMinimumsLargerWindow() {
			t.Fatal()
		}
	})

	t.Run("NLargestMaximumsMoreExpectedThanPresent", func(t *testing.T) {
		if !C.TestNLargestMaximumsMoreExpectedThanPresent() {
			t.Fatal()
		}
	})

	t.Run("NLargestMaximumssMorePresentThanExpected", func(t *testing.T) {
		if !C.TestNLargestMaximumssMorePresentThanExpected() {
			t.Fatal()
		}
	})

	t.Run("NLargestMaximumsLargerWindow", func(t *testing.T) {
		if !C.TestNLargestMaximumsLargerWindow() {
			t.Fatal()
		}
	})

	t.Run("LeftRoot", func(t *testing.T) {
		if !C.TestLeftRoot() {
			t.Fatal()
		}
	})

}
