// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exerciseKind.sql

package dal

import (
	"context"

	"code.barbellmath.net/barbell-math/providentia/lib/types"
)

type BulkCreateExerciseKindWithIDParams struct {
	ID          types.ExerciseKind `json:"id"`
	Kind        string             `json:"kind"`
	Description string             `json:"description"`
}

const updateExerciseKindSerialCount = `-- name: UpdateExerciseKindSerialCount :exec
SELECT SETVAL(
	pg_get_serial_sequence('providentia.exercise_kind', 'id'),
	(SELECT MAX(id) FROM providentia.exercise_kind) + 1
)
`

func (q *Queries) UpdateExerciseKindSerialCount(ctx context.Context) error {
	_, err := q.db.Exec(ctx, updateExerciseKindSerialCount)
	return err
}
