// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dal

import (
	"github.com/barbell-math/providentia/lib/types"
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID        int64  `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
}

type Exercise struct {
	ID      int32               `json:"id"`
	Name    string              `json:"name"`
	KindID  types.ExerciseKind  `json:"kind_id"`
	FocusID types.ExerciseFocus `json:"focus_id"`
}

type ExerciseFocus struct {
	ID    int32  `json:"id"`
	Focus string `json:"focus"`
}

type ExerciseKind struct {
	ID          int32  `json:"id"`
	Kind        string `json:"kind"`
	Description string `json:"description"`
}

type ModelState struct {
	ID            int64   `json:"id"`
	ClientID      int64   `json:"client_id"`
	TrainingLogID int64   `json:"training_log_id"`
	ModelID       int32   `json:"model_id"`
	V1            float64 `json:"v1"`
	V2            float64 `json:"v2"`
	V3            float64 `json:"v3"`
	V4            float64 `json:"v4"`
	V5            float64 `json:"v5"`
	V6            float64 `json:"v6"`
	V7            float64 `json:"v7"`
	V8            float64 `json:"v8"`
	V9            float64 `json:"v9"`
	V10           float64 `json:"v10"`
	TimeFrame     int32   `json:"time_frame"`
	Mse           float64 `json:"mse"`
	PredWeight    float64 `json:"pred_weight"`
}

type ProvidentiaModel struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type TrainingLog struct {
	ID               int64       `json:"id"`
	ExerciseID       int32       `json:"exercise_id"`
	ExerciseKindID   int32       `json:"exercise_kind_id"`
	ExerciseFocusID  int32       `json:"exercise_focus_id"`
	ClientID         int64       `json:"client_id"`
	VideoID          int64       `json:"video_id"`
	DatePerformed    pgtype.Date `json:"date_performed"`
	Weight           float64     `json:"weight"`
	Sets             float64     `json:"sets"`
	Reps             int32       `json:"reps"`
	Effort           float64     `json:"effort"`
	InterSessionCntr int32       `json:"inter_session_cntr"`
	InterWorkoutCntr int32       `json:"inter_workout_cntr"`
	Volume           float64     `json:"volume"`
	Exertion         float64     `json:"exertion"`
	TotalReps        float64     `json:"total_reps"`
}

type VideoData struct {
	ID           int64       `json:"id"`
	Path         string      `json:"path"`
	Position     [][]float64 `json:"position"`
	Velocity     [][]float64 `json:"velocity"`
	Acceleration [][]float64 `json:"acceleration"`
	Force        [][]float64 `json:"force"`
	Impulse      [][]float64 `json:"impulse"`
}
