// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dal

import (
	"code.barbellmath.net/barbell-math/providentia/lib/types"
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID        int64  `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
}

type Exercise struct {
	ID      int32               `json:"id"`
	Name    string              `json:"name"`
	KindID  types.ExerciseKind  `json:"kind_id"`
	FocusID types.ExerciseFocus `json:"focus_id"`
}

type ExerciseFocus struct {
	ID    int32  `json:"id"`
	Focus string `json:"focus"`
}

type ExerciseKind struct {
	ID          int32  `json:"id"`
	Kind        string `json:"kind"`
	Description string `json:"description"`
}

type ModelState struct {
	ID            int64   `json:"id"`
	ClientID      int64   `json:"client_id"`
	TrainingLogID int64   `json:"training_log_id"`
	ModelID       int32   `json:"model_id"`
	V1            float64 `json:"v1"`
	V2            float64 `json:"v2"`
	V3            float64 `json:"v3"`
	V4            float64 `json:"v4"`
	V5            float64 `json:"v5"`
	V6            float64 `json:"v6"`
	V7            float64 `json:"v7"`
	V8            float64 `json:"v8"`
	V9            float64 `json:"v9"`
	V10           float64 `json:"v10"`
	TimeFrame     int64   `json:"time_frame"`
	Mse           float64 `json:"mse"`
	PredWeight    float64 `json:"pred_weight"`
}

type PhysicsData struct {
	ID           int64                              `json:"id"`
	Path         []string                           `json:"path"`
	Time         [][]types.Second                   `json:"time"`
	Position     [][]types.Vec2[types.Meter]        `json:"position"`
	Velocity     [][]types.Vec2[types.MeterPerSec]  `json:"velocity"`
	Acceleration [][]types.Vec2[types.MeterPerSec2] `json:"acceleration"`
	Jerk         [][]types.Vec2[types.MeterPerSec3] `json:"jerk"`
	Force        [][]types.Vec2[types.Newton]       `json:"force"`
	Impulse      [][]types.Vec2[types.NewtonSec]    `json:"impulse"`
	Work         [][]types.Joule                    `json:"work"`
	Power        [][]types.Watt                     `json:"power"`
	RepSplits    [][]types.Split                    `json:"rep_splits"`
}

type ProvidentiaModel struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type TrainingLog struct {
	ID               int64          `json:"id"`
	ExerciseID       int32          `json:"exercise_id"`
	ClientID         int64          `json:"client_id"`
	PhysicsID        pgtype.Int8    `json:"physics_id"`
	DatePerformed    pgtype.Date    `json:"date_performed"`
	InterSessionCntr int16          `json:"inter_session_cntr"`
	InterWorkoutCntr int16          `json:"inter_workout_cntr"`
	Weight           types.Kilogram `json:"weight"`
	Sets             float64        `json:"sets"`
	Reps             int32          `json:"reps"`
	Effort           types.RPE      `json:"effort"`
	Volume           types.Kilogram `json:"volume"`
	Exertion         types.RPE      `json:"exertion"`
	TotalReps        float64        `json:"total_reps"`
}
