// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model.sql

package dal

import (
	"context"

	"code.barbellmath.net/barbell-math/providentia/lib/types"
)

type BulkCreateModelsWithIDParams struct {
	ID          types.ModelID `json:"id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
}

const updateModelSerialCount = `-- name: UpdateModelSerialCount :exec
SELECT SETVAL(
	pg_get_serial_sequence('providentia.model', 'id'),
	(SELECT MAX(id) FROM providentia.model) + 1
)
`

func (q *Queries) UpdateModelSerialCount(ctx context.Context) error {
	_, err := q.db.Exec(ctx, updateModelSerialCount)
	return err
}
