// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package dal

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BulkCreateClientsParams struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
}

type BulkCreateExerciseFocusWithIDParams struct {
	ID    int32  `json:"id"`
	Focus string `json:"focus"`
}

type BulkCreateExerciseKindWithIDParams struct {
	ID          int32  `json:"id"`
	Kind        string `json:"kind"`
	Description string `json:"description"`
}

type BulkCreateExerciseWithIDParams struct {
	ID      int32  `json:"id"`
	Name    string `json:"name"`
	KindID  int32  `json:"kind_id"`
	FocusID int32  `json:"focus_id"`
}

type BulkCreateModelStatesParams struct {
	ClientID      int64   `json:"client_id"`
	TrainingLogID int64   `json:"training_log_id"`
	ModelID       int32   `json:"model_id"`
	V1            float64 `json:"v1"`
	V2            float64 `json:"v2"`
	V3            float64 `json:"v3"`
	V4            float64 `json:"v4"`
	V5            float64 `json:"v5"`
	V6            float64 `json:"v6"`
	V7            float64 `json:"v7"`
	V8            float64 `json:"v8"`
	V9            float64 `json:"v9"`
	V10           float64 `json:"v10"`
	TimeFrame     int32   `json:"time_frame"`
	Mse           float64 `json:"mse"`
	PredWeight    float64 `json:"pred_weight"`
}

type BulkCreateModelsParams struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type BulkCreateTraingLogParams struct {
	ExerciseID       int32       `json:"exercise_id"`
	ExerciseKindID   int32       `json:"exercise_kind_id"`
	ExerciseFocusID  int32       `json:"exercise_focus_id"`
	ClientID         int64       `json:"client_id"`
	VideoID          int64       `json:"video_id"`
	DatePerformed    pgtype.Date `json:"date_performed"`
	Weight           float64     `json:"weight"`
	Sets             float64     `json:"sets"`
	Reps             int32       `json:"reps"`
	Effort           float64     `json:"effort"`
	InterSessionCntr int32       `json:"inter_session_cntr"`
	InterWorkoutCntr int32       `json:"inter_workout_cntr"`
}

type BulkCreateVideoDataWithIDParams struct {
	ID           int64       `json:"id"`
	Path         string      `json:"path"`
	Position     [][]float64 `json:"position"`
	Velocity     [][]float64 `json:"velocity"`
	Acceleration [][]float64 `json:"acceleration"`
	Force        [][]float64 `json:"force"`
	Impulse      [][]float64 `json:"impulse"`
}

const clientLastWorkoutDate = `-- name: ClientLastWorkoutDate :one
SELECT date_performed FROM providentia.training_log
WHERE client_id=$1
ORDER BY date_performed DESC LIMIT 1
`

func (q *Queries) ClientLastWorkoutDate(ctx context.Context, clientID int64) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, clientLastWorkoutDate, clientID)
	var date_performed pgtype.Date
	err := row.Scan(&date_performed)
	return date_performed, err
}

const clientTrainingLogDataDateRangeAscending = `-- name: ClientTrainingLogDataDateRangeAscending :many
SELECT
	providentia.training_log.id,
	providentia.training_log.exercise_id,
	providentia.training_log.exercise_kind_id,
	providentia.training_log.exercise_focus_id,
	($2::date-providentia.training_log.date_performed) AS days_since,
	providentia.training_log.weight,
	providentia.training_log.sets,
	providentia.training_log.reps,
	providentia.training_log.effort,
	providentia.training_log.inter_session_cntr,
	providentia.training_log.inter_workout_cntr
FROM providentia.training_log
WHERE providentia.training_log.client_id=$1
	AND providentia.training_log.date_performed<$2
ORDER BY
	-- These cannot be labeled with providentia.training_log because you will
	-- get a ` + "`" + `column reference "" not found` + "`" + ` error.
	date_performed ASC, id ASC
`

type ClientTrainingLogDataDateRangeAscendingParams struct {
	ClientID      int64       `json:"client_id"`
	DatePerformed pgtype.Date `json:"date_performed"`
}

type ClientTrainingLogDataDateRangeAscendingRow struct {
	ID               int64   `json:"id"`
	ExerciseID       int32   `json:"exercise_id"`
	ExerciseKindID   int32   `json:"exercise_kind_id"`
	ExerciseFocusID  int32   `json:"exercise_focus_id"`
	DaysSince        int32   `json:"days_since"`
	Weight           float64 `json:"weight"`
	Sets             float64 `json:"sets"`
	Reps             int32   `json:"reps"`
	Effort           float64 `json:"effort"`
	InterSessionCntr int32   `json:"inter_session_cntr"`
	InterWorkoutCntr int32   `json:"inter_workout_cntr"`
}

func (q *Queries) ClientTrainingLogDataDateRangeAscending(ctx context.Context, arg ClientTrainingLogDataDateRangeAscendingParams) ([]ClientTrainingLogDataDateRangeAscendingRow, error) {
	rows, err := q.db.Query(ctx, clientTrainingLogDataDateRangeAscending, arg.ClientID, arg.DatePerformed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientTrainingLogDataDateRangeAscendingRow
	for rows.Next() {
		var i ClientTrainingLogDataDateRangeAscendingRow
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.ExerciseKindID,
			&i.ExerciseFocusID,
			&i.DaysSince,
			&i.Weight,
			&i.Sets,
			&i.Reps,
			&i.Effort,
			&i.InterSessionCntr,
			&i.InterWorkoutCntr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClientIDFromEmail = `-- name: GetClientIDFromEmail :one
SELECT ID FROM providentia.client WHERE email=$1
`

func (q *Queries) GetClientIDFromEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRow(ctx, getClientIDFromEmail, email)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getExerciseIDs = `-- name: GetExerciseIDs :one
SELECT
	providentia.exercise.id AS exercise_id,
	providentia.exercise_kind.id AS kind_id,
	providentia.exercise_focus.id AS focus_id
FROM providentia.exercise
JOIN providentia.exercise_kind
	ON providentia.exercise.kind_id=providentia.exercise_kind.id
JOIN providentia.exercise_focus
	ON providentia.exercise.focus_id=providentia.exercise_focus.id
WHERE name=$1
`

type GetExerciseIDsRow struct {
	ExerciseID int32 `json:"exercise_id"`
	KindID     int32 `json:"kind_id"`
	FocusID    int32 `json:"focus_id"`
}

func (q *Queries) GetExerciseIDs(ctx context.Context, name string) (GetExerciseIDsRow, error) {
	row := q.db.QueryRow(ctx, getExerciseIDs, name)
	var i GetExerciseIDsRow
	err := row.Scan(&i.ExerciseID, &i.KindID, &i.FocusID)
	return i, err
}
