// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exerciseFocus.sql

package dal

import (
	"context"

	"code.barbellmath.net/barbell-math/providentia/lib/types"
)

type BulkCreateExerciseFocusWithIDParams struct {
	ID    types.ExerciseFocus `json:"id"`
	Focus string              `json:"focus"`
}

const updateExerciseFocusSerialCount = `-- name: UpdateExerciseFocusSerialCount :exec
SELECT SETVAL(
	pg_get_serial_sequence('providentia.exercise_focus', 'id'),
	(SELECT MAX(id) FROM providentia.exercise_focus) + 1
)
`

func (q *Queries) UpdateExerciseFocusSerialCount(ctx context.Context) error {
	_, err := q.db.Exec(ctx, updateExerciseFocusSerialCount)
	return err
}
