// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hyperparams.sql

package dal

import (
	"context"

	"code.barbellmath.net/barbell-math/providentia/lib/types"
)

type BulkCreateHyperparamsParams struct {
	ModelID types.ModelID `json:"model_id"`
	Version int32         `json:"version"`
	Params  []byte        `json:"params"`
}

type BulkCreateHyperparamsWithIDParams struct {
	ID      int32         `json:"id"`
	ModelID types.ModelID `json:"model_id"`
	Version int32         `json:"version"`
	Params  []byte        `json:"params"`
}

const deleteHyperparamsByVersionFor = `-- name: DeleteHyperparamsByVersionFor :one
WITH deleted_hyperparams AS (
	DELETE FROM providentia.hyperparams
	WHERE model_id=$1 AND version = ANY($2::INT4[])
	RETURNING id
) SELECT COUNT(*) FROM deleted_hyperparams
`

type DeleteHyperparamsByVersionForParams struct {
	ModelID  types.ModelID `json:"model_id"`
	Versions []int32       `json:"versions"`
}

func (q *Queries) DeleteHyperparamsByVersionFor(ctx context.Context, arg DeleteHyperparamsByVersionForParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteHyperparamsByVersionFor, arg.ModelID, arg.Versions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findHyperparamsByVersionFor = `-- name: FindHyperparamsByVersionFor :many
SELECT
	providentia.hyperparams.version,
	providentia.hyperparams.params,
	ord::INT8
FROM providentia.hyperparams
JOIN UNNEST($2::INT4[])
WITH ORDINALITY t(version, ord)
USING (version)
WHERE model_id=$1
ORDER BY ord
`

type FindHyperparamsByVersionForParams struct {
	ModelID  types.ModelID `json:"model_id"`
	Versions []int32       `json:"versions"`
}

type FindHyperparamsByVersionForRow struct {
	Version int32  `json:"version"`
	Params  []byte `json:"params"`
	Ord     int64  `json:"ord"`
}

// Note: this is different from GetHyperparamsByVersionFor because it returns a
// ordinal value. The ordinal value allows for checking that the requested
// hyperparameters existed in the database.
func (q *Queries) FindHyperparamsByVersionFor(ctx context.Context, arg FindHyperparamsByVersionForParams) ([]FindHyperparamsByVersionForRow, error) {
	rows, err := q.db.Query(ctx, findHyperparamsByVersionFor, arg.ModelID, arg.Versions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindHyperparamsByVersionForRow
	for rows.Next() {
		var i FindHyperparamsByVersionForRow
		if err := rows.Scan(&i.Version, &i.Params, &i.Ord); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHyperparamsByVersionFor = `-- name: GetHyperparamsByVersionFor :many
SELECT
	providentia.hyperparams.version,
	providentia.hyperparams.params
FROM providentia.hyperparams
JOIN UNNEST($2::INT4[])
WITH ORDINALITY t(version, ord)
USING (version)
WHERE model_id=$1
ORDER BY ord
`

type GetHyperparamsByVersionForParams struct {
	ModelID  types.ModelID `json:"model_id"`
	Versions []int32       `json:"versions"`
}

type GetHyperparamsByVersionForRow struct {
	Version int32  `json:"version"`
	Params  []byte `json:"params"`
}

func (q *Queries) GetHyperparamsByVersionFor(ctx context.Context, arg GetHyperparamsByVersionForParams) ([]GetHyperparamsByVersionForRow, error) {
	rows, err := q.db.Query(ctx, getHyperparamsByVersionFor, arg.ModelID, arg.Versions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHyperparamsByVersionForRow
	for rows.Next() {
		var i GetHyperparamsByVersionForRow
		if err := rows.Scan(&i.Version, &i.Params); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNumHyperparams = `-- name: GetNumHyperparams :one
SELECT COUNT(*) FROM providentia.hyperparams
`

func (q *Queries) GetNumHyperparams(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getNumHyperparams)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getNumHyperparamsFor = `-- name: GetNumHyperparamsFor :one
SELECT COUNT(*) FROM providentia.hyperparams
WHERE providentia.hyperparams.model_id=$1
`

func (q *Queries) GetNumHyperparamsFor(ctx context.Context, modelID types.ModelID) (int64, error) {
	row := q.db.QueryRow(ctx, getNumHyperparamsFor, modelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateHyperparamsSerialCount = `-- name: UpdateHyperparamsSerialCount :exec
SELECT SETVAL(
	pg_get_serial_sequence('providentia.hyperparams', 'id'),
	(SELECT MAX(id) FROM providentia.hyperparams) + 1
)
`

func (q *Queries) UpdateHyperparamsSerialCount(ctx context.Context) error {
	_, err := q.db.Exec(ctx, updateHyperparamsSerialCount)
	return err
}
