// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dal

import (
	"code.barbellmath.net/barbell-math/providentia/lib/types"
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID        int64  `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
}

type Exercise struct {
	ID      int32               `json:"id"`
	Name    string              `json:"name"`
	KindID  types.ExerciseKind  `json:"kind_id"`
	FocusID types.ExerciseFocus `json:"focus_id"`
}

type ExerciseFocus struct {
	ID    types.ExerciseFocus `json:"id"`
	Focus string              `json:"focus"`
}

type ExerciseKind struct {
	ID          types.ExerciseKind `json:"id"`
	Kind        string             `json:"kind"`
	Description string             `json:"description"`
}

type Hyperparam struct {
	ID      int32         `json:"id"`
	ModelID types.ModelID `json:"model_id"`
	Version int32         `json:"version"`
	Params  []byte        `json:"params"`
}

type ModelState struct {
	ID            int64   `json:"id"`
	ClientID      int64   `json:"client_id"`
	TrainingLogID int64   `json:"training_log_id"`
	HyperparamsID int32   `json:"hyperparams_id"`
	V1            float64 `json:"v1"`
	V2            float64 `json:"v2"`
	V3            float64 `json:"v3"`
	V4            float64 `json:"v4"`
	V5            float64 `json:"v5"`
	V6            float64 `json:"v6"`
	V7            float64 `json:"v7"`
	V8            float64 `json:"v8"`
	V9            float64 `json:"v9"`
	V10           float64 `json:"v10"`
	TimeFrame     int64   `json:"time_frame"`
	Mse           float64 `json:"mse"`
	PredWeight    float64 `json:"pred_weight"`
}

type PhysicsData struct {
	ID             int64                                                   `json:"id"`
	Path           []string                                                `json:"path"`
	BarPathCalcID  int32                                                   `json:"bar_path_calc_id"`
	BarPathTrackID pgtype.Int4                                             `json:"bar_path_track_id"`
	Time           [][]types.Second                                        `json:"time"`
	Position       [][]types.Vec2[types.Meter, types.Meter]                `json:"position"`
	Velocity       [][]types.Vec2[types.MeterPerSec, types.MeterPerSec]    `json:"velocity"`
	Acceleration   [][]types.Vec2[types.MeterPerSec2, types.MeterPerSec2]  `json:"acceleration"`
	Jerk           [][]types.Vec2[types.MeterPerSec3, types.MeterPerSec3]  `json:"jerk"`
	Force          [][]types.Vec2[types.Newton, types.Newton]              `json:"force"`
	Impulse        [][]types.Vec2[types.NewtonSec, types.NewtonSec]        `json:"impulse"`
	Work           [][]types.Joule                                         `json:"work"`
	Power          [][]types.Watt                                          `json:"power"`
	RepSplits      [][]types.Split                                         `json:"rep_splits"`
	MinVel         [][]types.PointInTime[types.Second, types.MeterPerSec]  `json:"min_vel"`
	MaxVel         [][]types.PointInTime[types.Second, types.MeterPerSec]  `json:"max_vel"`
	MinAcc         [][]types.PointInTime[types.Second, types.MeterPerSec2] `json:"min_acc"`
	MaxAcc         [][]types.PointInTime[types.Second, types.MeterPerSec2] `json:"max_acc"`
	MinForce       [][]types.PointInTime[types.Second, types.Newton]       `json:"min_force"`
	MaxForce       [][]types.PointInTime[types.Second, types.Newton]       `json:"max_force"`
	MinImpulse     [][]types.PointInTime[types.Second, types.NewtonSec]    `json:"min_impulse"`
	MaxImpulse     [][]types.PointInTime[types.Second, types.NewtonSec]    `json:"max_impulse"`
	AvgWork        [][]types.Joule                                         `json:"avg_work"`
	MinWork        [][]types.PointInTime[types.Second, types.Joule]        `json:"min_work"`
	MaxWork        [][]types.PointInTime[types.Second, types.Joule]        `json:"max_work"`
	AvgPower       [][]types.Watt                                          `json:"avg_power"`
	MinPower       [][]types.PointInTime[types.Second, types.Watt]         `json:"min_power"`
	MaxPower       [][]types.PointInTime[types.Second, types.Watt]         `json:"max_power"`
}

type ProvidentiaModel struct {
	ID          types.ModelID `json:"id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
}

type TrainingLog struct {
	ID               int64          `json:"id"`
	ExerciseID       int32          `json:"exercise_id"`
	ClientID         int64          `json:"client_id"`
	PhysicsID        pgtype.Int8    `json:"physics_id"`
	DatePerformed    pgtype.Date    `json:"date_performed"`
	InterSessionCntr int16          `json:"inter_session_cntr"`
	InterWorkoutCntr int16          `json:"inter_workout_cntr"`
	Weight           types.Kilogram `json:"weight"`
	Sets             float64        `json:"sets"`
	Reps             int32          `json:"reps"`
	Effort           types.RPE      `json:"effort"`
	Volume           types.Kilogram `json:"volume"`
	Exertion         types.RPE      `json:"exertion"`
	TotalReps        float64        `json:"total_reps"`
}
