#ifndef CGO_STRUCTS
#define CGO_STRUCTS

// File generated by cgoStructGen - DO NOT EDIT
// Struct definitions generated for C from Go struct definitions

#include <math.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

	typedef struct accVec2{
		double_t X;
		double_t Y;
	} accVec2_t;

	typedef struct barPathCalcConf{
		int32_t ApproxErr;
	} barPathCalcConf_t;

	typedef struct forceVec2{
		double_t X;
		double_t Y;
	} forceVec2_t;

	typedef struct impulseVec2{
		double_t X;
		double_t Y;
	} impulseVec2_t;

	typedef struct jerkVec2{
		double_t X;
		double_t Y;
	} jerkVec2_t;

	typedef struct physDataConf{
		uint64_t MinNumSamples;
		double_t TimeDeltaEps;
	} physDataConf_t;

	typedef struct posVec2{
		double_t X;
		double_t Y;
	} posVec2_t;

	typedef struct velVec2{
		double_t X;
		double_t Y;
	} velVec2_t;

	typedef struct workVec2{
		double_t X;
		double_t Y;
	} workVec2_t;

#ifdef __cplusplus
}
#endif

#endif
