// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package dal

import (
	"context"
)

// iteratorForBulkCreateExercise implements pgx.CopyFromSource.
type iteratorForBulkCreateExercise struct {
	rows                 []BulkCreateExerciseParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreateExercise) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreateExercise) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].Kindid,
		r.rows[0].Focusid,
	}, nil
}

func (r iteratorForBulkCreateExercise) Err() error {
	return nil
}

func (q *Queries) BulkCreateExercise(ctx context.Context, arg []BulkCreateExerciseParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"providentia", "exercise"}, []string{"id", "name", "kindid", "focusid"}, &iteratorForBulkCreateExercise{rows: arg})
}

// iteratorForBulkCreateExerciseFocus implements pgx.CopyFromSource.
type iteratorForBulkCreateExerciseFocus struct {
	rows                 []BulkCreateExerciseFocusParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreateExerciseFocus) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreateExerciseFocus) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Focus,
	}, nil
}

func (r iteratorForBulkCreateExerciseFocus) Err() error {
	return nil
}

func (q *Queries) BulkCreateExerciseFocus(ctx context.Context, arg []BulkCreateExerciseFocusParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"providentia", "exercisefocus"}, []string{"id", "focus"}, &iteratorForBulkCreateExerciseFocus{rows: arg})
}

// iteratorForBulkCreateExerciseKind implements pgx.CopyFromSource.
type iteratorForBulkCreateExerciseKind struct {
	rows                 []BulkCreateExerciseKindParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreateExerciseKind) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreateExerciseKind) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Kind,
		r.rows[0].Description,
	}, nil
}

func (r iteratorForBulkCreateExerciseKind) Err() error {
	return nil
}

func (q *Queries) BulkCreateExerciseKind(ctx context.Context, arg []BulkCreateExerciseKindParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"providentia", "exercisekind"}, []string{"id", "kind", "description"}, &iteratorForBulkCreateExerciseKind{rows: arg})
}
