// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dal

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID        int64
	Firstname string
	Lastname  string
	Email     string
}

type Exercise struct {
	ID      int32
	Name    string
	Kindid  int32
	Focusid int32
}

type ExerciseFocus struct {
	ID    int32
	Focus string
}

type ProvidentiaExercisekind struct {
	ID          int32
	Kind        string
	Description string
}

type TrainingLog struct {
	ID                int64
	Exercisekindid    int32
	Exercisefocusid   int32
	Clientid          int32
	Videoid           int64
	Dateperformed     pgtype.Date
	Weight            float64
	Sets              float64
	Reps              int32
	Effort            float64
	Interexercisecntr int32
	Interworkoutcntr  int32
	Volume            float64
	Efforts           float64
}

type VideoData struct {
	ID           int64
	Position     [][]float64
	Velocity     [][]float64
	Acceleration [][]float64
	Force        [][]float64
	Impulse      [][]float64
}
