// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package dal

type BulkCreateExerciseParams struct {
	ID      int32
	Name    string
	Kindid  int32
	Focusid int32
}

type BulkCreateExerciseFocusParams struct {
	ID    int32
	Focus string
}

type BulkCreateExerciseKindParams struct {
	ID          int32
	Kind        string
	Description string
}
