#ifndef CGO_STRUCTS
#define CGO_STRUCTS

// File generated by cgoStructGen - DO NOT EDIT
// Struct definitions generated for C from Go struct definitions

#include <math.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

	typedef struct modelState{
		int64_t ClientID;
		int64_t TrainingLogID;
		int32_t ModelID;
		double_t V1;
		double_t V2;
		double_t V3;
		double_t V4;
		double_t V5;
		double_t V6;
		double_t V7;
		double_t V8;
		double_t V9;
		double_t V10;
		int64_t TimeFrame;
		double_t Mse;
		double_t PredWeight;
	} modelState_t;

	typedef struct opts{
		double_t Alpha;
		double_t Beta;
		double_t Gamma;
		uint64_t MaxIters;
	} opts_t;

	typedef struct trainingLog{
		int64_t ID;
		int32_t ExerciseID;
		int32_t DaysSince;
		double_t Weight;
		double_t Sets;
		int32_t Reps;
		double_t Effort;
		int16_t InterSessionCntr;
		int16_t InterWorkoutCntr;
	} trainingLog_t;

#ifdef __cplusplus
}
#endif

#endif
