// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package barpathtracker

import (
	"fmt"
	"strings"
)

const (
	// NoBarPathTrackerErr is a BarPathTrackerErrCode of type NoBarPathTrackerErr.
	NoBarPathTrackerErr BarPathTrackerErrCode = iota
	// VAAPINotSupportedErr is a BarPathTrackerErrCode of type VAAPINotSupportedErr.
	VAAPINotSupportedErr
	// CouldNotAllocateAVPacketErr is a BarPathTrackerErrCode of type CouldNotAllocateAVPacketErr.
	CouldNotAllocateAVPacketErr
	// CouldNotOpenVideoFileErr is a BarPathTrackerErrCode of type CouldNotOpenVideoFileErr.
	CouldNotOpenVideoFileErr
	// CouldNotFindInputStreamInfoErr is a BarPathTrackerErrCode of type CouldNotFindInputStreamInfoErr.
	CouldNotFindInputStreamInfoErr
	// CouldNotFindVideoStreamErr is a BarPathTrackerErrCode of type CouldNotFindVideoStreamErr.
	CouldNotFindVideoStreamErr
	// DecoderDoesNotSupportVAAPIErr is a BarPathTrackerErrCode of type DecoderDoesNotSupportVAAPIErr.
	DecoderDoesNotSupportVAAPIErr
	// AVCodecParametersToCtxtErr is a BarPathTrackerErrCode of type AVCodecParametersToCtxtErr.
	AVCodecParametersToCtxtErr
	// CouldNotCreateHwDeviceErr is a BarPathTrackerErrCode of type CouldNotCreateHwDeviceErr.
	CouldNotCreateHwDeviceErr
	// CouldNotOpenCodecForStreamErr is a BarPathTrackerErrCode of type CouldNotOpenCodecForStreamErr.
	CouldNotOpenCodecForStreamErr
)

var ErrInvalidBarPathTrackerErrCode = fmt.Errorf("not a valid BarPathTrackerErrCode, try [%s]", strings.Join(_BarPathTrackerErrCodeNames, ", "))

const _BarPathTrackerErrCodeName = "NoBarPathTrackerErrVAAPINotSupportedErrCouldNotAllocateAVPacketErrCouldNotOpenVideoFileErrCouldNotFindInputStreamInfoErrCouldNotFindVideoStreamErrDecoderDoesNotSupportVAAPIErrAVCodecParametersToCtxtErrCouldNotCreateHwDeviceErrCouldNotOpenCodecForStreamErr"

var _BarPathTrackerErrCodeNames = []string{
	_BarPathTrackerErrCodeName[0:19],
	_BarPathTrackerErrCodeName[19:39],
	_BarPathTrackerErrCodeName[39:66],
	_BarPathTrackerErrCodeName[66:90],
	_BarPathTrackerErrCodeName[90:120],
	_BarPathTrackerErrCodeName[120:146],
	_BarPathTrackerErrCodeName[146:175],
	_BarPathTrackerErrCodeName[175:201],
	_BarPathTrackerErrCodeName[201:226],
	_BarPathTrackerErrCodeName[226:255],
}

// BarPathTrackerErrCodeNames returns a list of possible string values of BarPathTrackerErrCode.
func BarPathTrackerErrCodeNames() []string {
	tmp := make([]string, len(_BarPathTrackerErrCodeNames))
	copy(tmp, _BarPathTrackerErrCodeNames)
	return tmp
}

// BarPathTrackerErrCodeValues returns a list of the values for BarPathTrackerErrCode
func BarPathTrackerErrCodeValues() []BarPathTrackerErrCode {
	return []BarPathTrackerErrCode{
		NoBarPathTrackerErr,
		VAAPINotSupportedErr,
		CouldNotAllocateAVPacketErr,
		CouldNotOpenVideoFileErr,
		CouldNotFindInputStreamInfoErr,
		CouldNotFindVideoStreamErr,
		DecoderDoesNotSupportVAAPIErr,
		AVCodecParametersToCtxtErr,
		CouldNotCreateHwDeviceErr,
		CouldNotOpenCodecForStreamErr,
	}
}

var _BarPathTrackerErrCodeMap = map[BarPathTrackerErrCode]string{
	NoBarPathTrackerErr:            _BarPathTrackerErrCodeName[0:19],
	VAAPINotSupportedErr:           _BarPathTrackerErrCodeName[19:39],
	CouldNotAllocateAVPacketErr:    _BarPathTrackerErrCodeName[39:66],
	CouldNotOpenVideoFileErr:       _BarPathTrackerErrCodeName[66:90],
	CouldNotFindInputStreamInfoErr: _BarPathTrackerErrCodeName[90:120],
	CouldNotFindVideoStreamErr:     _BarPathTrackerErrCodeName[120:146],
	DecoderDoesNotSupportVAAPIErr:  _BarPathTrackerErrCodeName[146:175],
	AVCodecParametersToCtxtErr:     _BarPathTrackerErrCodeName[175:201],
	CouldNotCreateHwDeviceErr:      _BarPathTrackerErrCodeName[201:226],
	CouldNotOpenCodecForStreamErr:  _BarPathTrackerErrCodeName[226:255],
}

// String implements the Stringer interface.
func (x BarPathTrackerErrCode) String() string {
	if str, ok := _BarPathTrackerErrCodeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("BarPathTrackerErrCode(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x BarPathTrackerErrCode) IsValid() bool {
	_, ok := _BarPathTrackerErrCodeMap[x]
	return ok
}

var _BarPathTrackerErrCodeValue = map[string]BarPathTrackerErrCode{
	_BarPathTrackerErrCodeName[0:19]:                     NoBarPathTrackerErr,
	strings.ToLower(_BarPathTrackerErrCodeName[0:19]):    NoBarPathTrackerErr,
	_BarPathTrackerErrCodeName[19:39]:                    VAAPINotSupportedErr,
	strings.ToLower(_BarPathTrackerErrCodeName[19:39]):   VAAPINotSupportedErr,
	_BarPathTrackerErrCodeName[39:66]:                    CouldNotAllocateAVPacketErr,
	strings.ToLower(_BarPathTrackerErrCodeName[39:66]):   CouldNotAllocateAVPacketErr,
	_BarPathTrackerErrCodeName[66:90]:                    CouldNotOpenVideoFileErr,
	strings.ToLower(_BarPathTrackerErrCodeName[66:90]):   CouldNotOpenVideoFileErr,
	_BarPathTrackerErrCodeName[90:120]:                   CouldNotFindInputStreamInfoErr,
	strings.ToLower(_BarPathTrackerErrCodeName[90:120]):  CouldNotFindInputStreamInfoErr,
	_BarPathTrackerErrCodeName[120:146]:                  CouldNotFindVideoStreamErr,
	strings.ToLower(_BarPathTrackerErrCodeName[120:146]): CouldNotFindVideoStreamErr,
	_BarPathTrackerErrCodeName[146:175]:                  DecoderDoesNotSupportVAAPIErr,
	strings.ToLower(_BarPathTrackerErrCodeName[146:175]): DecoderDoesNotSupportVAAPIErr,
	_BarPathTrackerErrCodeName[175:201]:                  AVCodecParametersToCtxtErr,
	strings.ToLower(_BarPathTrackerErrCodeName[175:201]): AVCodecParametersToCtxtErr,
	_BarPathTrackerErrCodeName[201:226]:                  CouldNotCreateHwDeviceErr,
	strings.ToLower(_BarPathTrackerErrCodeName[201:226]): CouldNotCreateHwDeviceErr,
	_BarPathTrackerErrCodeName[226:255]:                  CouldNotOpenCodecForStreamErr,
	strings.ToLower(_BarPathTrackerErrCodeName[226:255]): CouldNotOpenCodecForStreamErr,
}

// ParseBarPathTrackerErrCode attempts to convert a string to a BarPathTrackerErrCode.
func ParseBarPathTrackerErrCode(name string) (BarPathTrackerErrCode, error) {
	if x, ok := _BarPathTrackerErrCodeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _BarPathTrackerErrCodeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return BarPathTrackerErrCode(0), fmt.Errorf("%s is %w", name, ErrInvalidBarPathTrackerErrCode)
}

// MarshalText implements the text marshaller method.
func (x BarPathTrackerErrCode) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *BarPathTrackerErrCode) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseBarPathTrackerErrCode(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *BarPathTrackerErrCode) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
