// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package barpathtracker

import (
	"fmt"
	"strings"
)

const (
	// NoBarPathTrackerErr is a BarPathTrackerErrCode of type NoBarPathTrackerErr.
	NoBarPathTrackerErr BarPathTrackerErrCode = iota
)

var ErrInvalidBarPathTrackerErrCode = fmt.Errorf("not a valid BarPathTrackerErrCode, try [%s]", strings.Join(_BarPathTrackerErrCodeNames, ", "))

const _BarPathTrackerErrCodeName = "NoBarPathTrackerErr"

var _BarPathTrackerErrCodeNames = []string{
	_BarPathTrackerErrCodeName[0:19],
}

// BarPathTrackerErrCodeNames returns a list of possible string values of BarPathTrackerErrCode.
func BarPathTrackerErrCodeNames() []string {
	tmp := make([]string, len(_BarPathTrackerErrCodeNames))
	copy(tmp, _BarPathTrackerErrCodeNames)
	return tmp
}

// BarPathTrackerErrCodeValues returns a list of the values for BarPathTrackerErrCode
func BarPathTrackerErrCodeValues() []BarPathTrackerErrCode {
	return []BarPathTrackerErrCode{
		NoBarPathTrackerErr,
	}
}

var _BarPathTrackerErrCodeMap = map[BarPathTrackerErrCode]string{
	NoBarPathTrackerErr: _BarPathTrackerErrCodeName[0:19],
}

// String implements the Stringer interface.
func (x BarPathTrackerErrCode) String() string {
	if str, ok := _BarPathTrackerErrCodeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("BarPathTrackerErrCode(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x BarPathTrackerErrCode) IsValid() bool {
	_, ok := _BarPathTrackerErrCodeMap[x]
	return ok
}

var _BarPathTrackerErrCodeValue = map[string]BarPathTrackerErrCode{
	_BarPathTrackerErrCodeName[0:19]:                  NoBarPathTrackerErr,
	strings.ToLower(_BarPathTrackerErrCodeName[0:19]): NoBarPathTrackerErr,
}

// ParseBarPathTrackerErrCode attempts to convert a string to a BarPathTrackerErrCode.
func ParseBarPathTrackerErrCode(name string) (BarPathTrackerErrCode, error) {
	if x, ok := _BarPathTrackerErrCodeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _BarPathTrackerErrCodeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return BarPathTrackerErrCode(0), fmt.Errorf("%s is %w", name, ErrInvalidBarPathTrackerErrCode)
}

// MarshalText implements the text marshaller method.
func (x BarPathTrackerErrCode) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *BarPathTrackerErrCode) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseBarPathTrackerErrCode(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *BarPathTrackerErrCode) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
