#ifndef CGO_GLUE_INCLUDE_GUARD
#define CGO_GLUE_INCLUDE_GUARD

// File generated by cgoGlue - DO NOT EDIT
// Struct definitions generated for C from Go struct definitions

#include <math.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

	typedef struct {
		int32_t v;
	} ApproximationError_t;
	const ApproximationError_t SecondOrder = { .v=2 };
	const ApproximationError_t FourthOrder = { .v=4 };

	typedef struct {
		int64_t v;
	} BarPathCalcErrCode_t;
	const BarPathCalcErrCode_t NoErr = { .v=0 };
	const BarPathCalcErrCode_t TimeSeriesNotIncreasingErr = { .v=1 };
	const BarPathCalcErrCode_t TimeSeriesNotMonotonicErr = { .v=2 };
	const BarPathCalcErrCode_t InvalidApproximationErrErr = { .v=3 };

	typedef struct accVec2{
		double_t X;
		double_t Y;
	} accVec2_t;

	typedef struct barPathCalcConf{
		ApproximationError_t ApproxErr;
	} barPathCalcConf_t;

	typedef struct forceVec2{
		double_t X;
		double_t Y;
	} forceVec2_t;

	typedef struct impulseVec2{
		double_t X;
		double_t Y;
	} impulseVec2_t;

	typedef struct jerkVec2{
		double_t X;
		double_t Y;
	} jerkVec2_t;

	typedef struct physDataConf{
		uint64_t MinNumSamples;
		double_t TimeDeltaEps;
	} physDataConf_t;

	typedef struct posVec2{
		double_t X;
		double_t Y;
	} posVec2_t;

	typedef struct velVec2{
		double_t X;
		double_t Y;
	} velVec2_t;

	typedef struct workVec2{
		double_t X;
		double_t Y;
	} workVec2_t;

#ifdef __cplusplus
}
#endif

#endif
