#ifndef CGO_GLUE_INCLUDE_GUARD
#define CGO_GLUE_INCLUDE_GUARD

// File generated by cgoGlue - DO NOT EDIT
// Type definitions generated for C from Go type definitions

#include <math.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

	enum ApproximationError_t : int32_t {
		SecondOrder = 2,
		FourthOrder = 4
	};

	enum BarPathCalcErrCode_t : int64_t {
		NoErr = 0,
		TimeSeriesNotIncreasingErr = 1,
		TimeSeriesNotMonotonicErr = 2,
		InvalidApproximationErrErr = 3
	};

	typedef struct accVec2{
		double_t X;
		double_t Y;
	} accVec2_t;

	typedef struct barPathCalcConf{
		enum ApproximationError_t ApproxErr;
		double_t SmootherWeight1;
		double_t SmootherWeight2;
		double_t SmootherWeight3;
		double_t SmootherWeight4;
		double_t SmootherWeight5;
	} barPathCalcConf_t;

	typedef struct forceVec2{
		double_t X;
		double_t Y;
	} forceVec2_t;

	typedef struct impulseVec2{
		double_t X;
		double_t Y;
	} impulseVec2_t;

	typedef struct jerkVec2{
		double_t X;
		double_t Y;
	} jerkVec2_t;

	typedef struct physDataConf{
		uint64_t MinNumSamples;
		double_t TimeDeltaEps;
	} physDataConf_t;

	typedef struct posVec2{
		double_t X;
		double_t Y;
	} posVec2_t;

	typedef struct velVec2{
		double_t X;
		double_t Y;
	} velVec2_t;

#ifdef __cplusplus
}
#endif

#endif
